version: '3.7'

services:
  feedbacky-client:
    container_name: feedbacky-client
    build:
      context: frontend
      dockerfile: ${PWD}/client/Dockerfile-prod
      args:
        - REACT_APP_SERVER_IP_ADDRESS=${REACT_APP_SERVER_IP_ADDRESS}
        - REACT_APP_PUBLIC_API_PORT=${REACT_APP_PUBLIC_API_PORT}
    ports:
      - '80:80'
    volumes:
      - feedbacky-data:/storage-data
  feedbacky-server:
    container_name: feedbacky-server
    build:
      context: backend
      dockerfile: ${PWD}/server/Dockerfile
    ports:
      - '8095:8080'
    links:
      - feedbacky-client
    volumes:
      - feedbacky-data:/storage-data

volumes:
  feedbacky-data: