version: '3.7'

services:
  feedbacky-client:
    container_name: feedbacky-client
    build:
      context: client
      dockerfile: ./Dockerfile
      args:
        - REACT_APP_SERVER_IP_ADDRESS=${REACT_APP_SERVER_IP_ADDRESS}
        - REACT_APP_PUBLIC_API_PORT=${REACT_APP_PUBLIC_API_PORT}
    ports:
      - '80:80'
    links:
      - feedbacky-server
    volumes:
      - feedbacky-data:/storage-data
  feedbacky-server:
    container_name: feedbacky-server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - '8095:8080'
    volumes:
      - feedbacky-data:/storage-data
    env_file:
      - .env

volumes:
  feedbacky-data: