version: '3.7'

services:
  feedbacky-client:
    container_name: feedbacky-client
    build:
      context: frontend
      dockerfile: ${PWD}/frontend/Dockerfile-prod
    ports:
      - '80:80'
    volumes:
      - feedbacky-data:/storage-data
  feedbacky-server:
    container_name: feedbacky-server
    build:
      context: backend
      dockerfile: ${PWD}/backend/Dockerfile
    ports:
      - '8095:8080'
    links:
      - feedbacky-client
    volumes:
      - feedbacky-data:/storage-data

volumes:
  feedbacky-data: